/**
 * Mappatura tag Open Food Facts → codici allergene AllerTgy.
 */
export const OFF_ALLERGEN_MAP: Record<string, string[]> = {
  // Allergeni obbligatori UE
  'en:gluten': ['glutine'],
  'en:wheat': ['glutine'],
  'en:rye': ['glutine', 'segale'],
  'en:barley': ['glutine', 'orzo'],
  'en:oats': ['glutine', 'avena'],
  'en:spelt': ['glutine', 'farro'],
  'en:crustaceans': ['crostacei'],
  'en:eggs': ['uova'],
  'en:fish': ['pesce'],
  'en:peanuts': ['arachidi'],
  'en:soybeans': ['soia'],
  'en:milk': ['latte'],
  'en:lactose': ['latte'],
  'en:nuts': ['frutta_a_guscio'],
  'en:almond': ['frutta_a_guscio', 'mandorle'],
  'en:hazelnut': ['frutta_a_guscio', 'nocciole'],
  'en:walnut': ['frutta_a_guscio', 'noci'],
  'en:cashew': ['frutta_a_guscio', 'anacardi'],
  'en:pecan': ['frutta_a_guscio', 'noci_pecan'],
  'en:brazil-nut': ['frutta_a_guscio', 'noci_brasiliane'],
  'en:pistachio': ['frutta_a_guscio', 'pistacchi'],
  'en:macadamia': ['frutta_a_guscio', 'macadamia'],
  'en:celery': ['sedano'],
  'en:mustard': ['senape'],
  'en:sesame-seeds': ['sesamo'],
  'en:sulphur-dioxide-and-sulphites': ['solfiti'],
  'en:lupin': ['lupini'],
  'en:molluscs': ['molluschi'],

  // Ingredienti specifici (standardizzati come tag en: da OFF)
  'en:strawberry': ['fragole'],
  'en:kiwi': ['kiwi'],
  'en:apple': ['mela'],
  'en:peach': ['pesca'],
  'en:orange': ['arancia', 'agrumi'],
  'en:lemon': ['limone', 'agrumi'],
  'en:banana': ['banana'],
  'en:grape': ['uva'],
  'en:watermelon': ['anguria'],
  'en:melon': ['melone'],
  'en:pineapple': ['ananas'],
  'en:mango': ['mango'],
  'en:avocado': ['avocado'],
  'en:apricot': ['albicocca'],
  'en:cherry': ['ciliegia'],
  'en:pear': ['pera'],
  'en:plum': ['prugna'],
  'en:raspberry': ['lamponi'],
  'en:blueberry': ['mirtilli'],
  'en:coconut': ['cocco'],
  'en:tomato': ['pomodoro'],
  'en:garlic': ['aglio'],
  'en:onion': ['cipolla'],
  'en:carrot': ['carota'],
  'en:mushroom': ['funghi'],
  'en:corn': ['mais'],
  'en:chili-pepper': ['peperoncino'],
  'en:bell-pepper': ['peperone'],
  'en:eggplant': ['melanzana'],
  'en:zucchini': ['zucchina'],
  'en:spinach': ['spinaci'],
  'en:broccoli': ['broccoli'],
  'en:cauliflower': ['cavolfiore'],
  'en:cabbage': ['cavolo'],
  'en:potato': ['patata'],
  'en:peas': ['piselli'],
  'en:beans': ['fagioli'],
  'en:lentil': ['lenticchie'],
  'en:cucumber': ['cetriolo'],
  'en:lettuce': ['lattuga'],
  'en:arugula': ['rucola'],
  'en:beetroot': ['barbabietola'],
  'en:fennel': ['finocchio'],
  'en:asparagus': ['asparagi'],
  'en:artichoke': ['carciofi'],
  'en:leek': ['porri'],
  'en:rice': ['riso'],
  'en:quinoa': ['quinoa'],
  'en:buckwheat': ['grano_saraceno'],
  'en:teff': ['teff'],
  'en:amaranth': ['amaranto'],
  'en:cinnamon': ['cannella'],
  'en:vanilla': ['vaniglia'],
  'en:pepper': ['pepe'],
  'en:curry': ['curry'],
  'en:ginger': ['zenzero'],
  'en:nutmeg': ['noce_moscata'],
  'en:clove': ['chiodi_di_garofano'],
  'en:paprika': ['paprika'],
  'en:cumin': ['cumino'],
  'en:oregano': ['origano'],
  'en:rosemary': ['rosmarino'],
  'en:thyme': ['timo'],
  'en:sage': ['salvia'],
  'en:anise': ['anice'],
  'en:turmeric': ['curcuma'],
  'en:coriander': ['coriandolo'],
  'en:bay-leaf': ['alloro'],
  'en:caffeine': ['caffeina'],
  'en:alcohol': ['alcool'],
};

// Parole chiave in italiano per ciascun allergene (per evidenziarle negli ingredienti testuali)
export const ALLERGEN_KEYWORDS: Record<string, string[]> = {
  glutine: ['glutine', 'frumento', 'grano', 'orzo', 'avena', 'segale', 'farro', 'saraceno', 'kamut', 'spelta', 'cereali', 'malto'],
  latte: ['latte', 'lattosio', 'burro', 'panna', 'formaggio', 'casein', 'lattico', 'lattica', 'yogurt', 'siero'],
  uova: ['uova', 'uovo', 'albume', 'tuorlo', 'maionese'],
  arachidi: ['arachid', 'spagnolette'],
  soia: ['soia', 'lecitina de soia', 'lecitina di soia'],
  frutta_a_guscio: ['mandorl', 'nocciol', 'nocin', 'noci', 'anacard', 'pecan', 'pistacchio', 'pistacchi', 'macadamia', 'pinoli', 'castagne', 'anacardo'],
  crostacei: ['gamber', 'scamp', 'aragost', 'astice', 'mancora', 'granchio', 'crostacei'],
  pesce: ['pesce', 'tonno', 'salmone', 'merluzzo', 'acciug', 'alici', 'pesci'],
  sedano: ['sedano'],
  senape: ['senape'],
  sesamo: ['sesamo'],
  solfiti: ['solfiti', 'anidride solforosa', 'e220', 'e221', 'e222', 'e223', 'e224', 'e226', 'e227', 'e228'],
  lupini: ['lupin'],
  molluschi: ['cozz', 'vongol', 'polpo', 'seppi', 'calamar', 'molluschi', 'ostric', 'lumach'],
  pomodoro: ['pomodor'],
  aglio: ['aglio'],
  cipolla: ['cipolla'],
  fragole: ['fragol'],
  kiwi: ['kiwi'],
  mela: ['mel'],
  pesca: ['pesc'],
  arancia: ['aranci'],
  limone: ['limon'],
  banana: ['banan'],
  carota: ['carot'],
  funghi: ['fungh', 'champignon', 'porcin'],
  mais: ['mais', 'granturco'],
  peperoncino: ['peperoncin'],
  peperone: ['peperon'],
  melanzana: ['melanzan'],
  zucchina: ['zucchin'],
  spinaci: ['spinac'],
  broccoli: ['broccol'],
  cavolfiore: ['cavolfior'],
  cavolo: ['cavol'],
  patata: ['patat'],
  piselli: ['pisell'],
  fagioli: ['fagiol'],
  lenticchie: ['lenticch'],
  cetriolo: ['cetriol'],
  lattuga: ['lattug', 'insalat'],
  rucola: ['rucol'],
  barbabietola: ['barbabietol'],
  finocchio: ['finocch'],
  asparagi: ['asparag'],
  carciofi: ['carciof'],
  porri: ['porr'],
  riso: ['riso'],
  quinoa: ['quinoa'],
  cinnamon: ['cannell'],
  vaniglia: ['vanigl'],
  pepe: ['pepe'],
  curry: ['curry'],
  zenzero: ['zenzer'],
  caffeina: ['caffein', 'caffè'],
  alcool: ['alcool', 'alcol', 'etilico'],
};
